CREATE TABLE EMPREGADOS(
    MATRICULA VARCHAR2(20) PRIMARY KEY,
    NOME VARCHAR2(50) NOT NULL,
    ENDERECO VARCHAR2(100) NOT NULL,
    FUNCAO VARCHAR2(20) NOT NULL,
    SALARIO NUMBER(10, 2) NOT NULL
);

INSERT ALL
  INTO EMPREGADOS (MATRICULA, NOME, ENDERECO, FUNCAO, SALARIO) VALUES ('102', 'Bruno Reis', 'Av. Brasil 450 Liberdade', 'Técnico', 4200.00)
  INTO EMPREGADOS (MATRICULA, NOME, ENDERECO, FUNCAO, SALARIO) VALUES ('103', 'Carla Dias', 'R. Verde 89 Jardim América', 'Engenheira', 7000.00)
  INTO EMPREGADOS (MATRICULA, NOME, ENDERECO, FUNCAO, SALARIO) VALUES ('104', 'Diego Souza', 'R. Azul 77 Santa Lúcia', 'Analista', 5500.00)
  INTO EMPREGADOS (MATRICULA, NOME, ENDERECO, FUNCAO, SALARIO) VALUES ('105', 'Elisa Melo', 'R. Norte 23 Boa Vista', 'Auxiliar', 2800.00)
  INTO EMPREGADOS (MATRICULA, NOME, ENDERECO, FUNCAO, SALARIO) VALUES ('106', 'Fábio Cruz', 'Av. Central 300 Centro', 'Engenheiro', 7200.00)
  INTO EMPREGADOS (MATRICULA, NOME, ENDERECO, FUNCAO, SALARIO) VALUES ('107', 'Giovana Paz', 'R. Sul 11 Morumbi', 'Técnica', 4300.00)
  INTO EMPREGADOS (MATRICULA, NOME, ENDERECO, FUNCAO, SALARIO) VALUES ('108', 'Hugo Nunes', 'R. Leste 65 Planalto', 'Gerente', 9500.00)
  INTO EMPREGADOS (MATRICULA, NOME, ENDERECO, FUNCAO, SALARIO) VALUES ('109', 'Isabela Fonseca', 'R. Oeste 41 Estação', 'Secretária', 3300.00)
  INTO EMPREGADOS (MATRICULA, NOME, ENDERECO, FUNCAO, SALARIO) VALUES ('110', 'João Freitas', 'R. Lagoa 100 Nova Esperança', 'Analista', 5700.00)
SELECT * FROM DUAL;

CREATE TABLE DEPENDENTES(
    CODIGO VARCHAR2(20) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    MATRICULA_TITULAR VARCHAR2(20) NOT NULL,
    RELACAO VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_MATRICULA_TITULAR FOREIGN KEY (MATRICULA_TITULAR) REFERENCES EMPREGADOS(MATRICULA)
);

INSERT ALL
  INTO DEPENDENTES (CODIGO, NOME, MATRICULA_TITULAR, RELACAO) VALUES ('D001', 'Lucas Reis', 102, 'Filho')
  INTO DEPENDENTES (CODIGO, NOME, MATRICULA_TITULAR, RELACAO) VALUES ('D002', 'Mariana Reis', 102, 'Filha')
  INTO DEPENDENTES (CODIGO, NOME, MATRICULA_TITULAR, RELACAO) VALUES ('D003', 'Paula Dias', 103, 'Esposa')
  INTO DEPENDENTES (CODIGO, NOME, MATRICULA_TITULAR, RELACAO) VALUES ('D004', 'Tiago Souza', 104, 'Filho')
  INTO DEPENDENTES (CODIGO, NOME, MATRICULA_TITULAR, RELACAO) VALUES ('D005', 'Fernanda Souza', 104, 'Filha')
  INTO DEPENDENTES (CODIGO, NOME, MATRICULA_TITULAR, RELACAO) VALUES ('D006', 'Clara Melo', 105, 'Filha')
  INTO DEPENDENTES (CODIGO, NOME, MATRICULA_TITULAR, RELACAO) VALUES ('D007', 'Roberto Cruz', 106, 'Filho')
  INTO DEPENDENTES (CODIGO, NOME, MATRICULA_TITULAR, RELACAO) VALUES ('D008', 'Juliana Cruz', 106, 'Esposa')
  INTO DEPENDENTES (CODIGO, NOME, MATRICULA_TITULAR, RELACAO) VALUES ('D009', 'Gustavo Paz', 107, 'Filho')
  INTO DEPENDENTES (CODIGO, NOME, MATRICULA_TITULAR, RELACAO) VALUES ('D010', 'Sofia Nunes', 108, 'Filha')
  INTO DEPENDENTES (CODIGO, NOME, MATRICULA_TITULAR, RELACAO) VALUES ('D011', 'Carlos Fonseca', 109, 'Filho')
  INTO DEPENDENTES (CODIGO, NOME, MATRICULA_TITULAR, RELACAO) VALUES ('D012', 'Letícia Freitas', 110, 'Esposa')
SELECT * FROM DUAL;

SELECT * FROM EMPREGADOS;
SELECT * FROM DEPENDENTES;

SELECT NOME, 
       (SELECT COUNT(*) FROM DEPENDENTES D WHERE D.MATRICULA_TITULAR = E.MATRICULA) AS QTD
FROM EMPREGADOS E;

SELECT E.NOME 
FROM EMPREGADOS E 
WHERE (
    SELECT COUNT(*) FROM DEPENDENTES D WHERE D.MATRICULA_TITULAR = E.MATRICULA
) >= 2;
