/* 1 - Crie, no seu banco de dados, a tabela abaixo chamada VENDAS, insira os valores
apresentados e em seguida escreva as consultas solicitadas abaixo. Todas as colunas
são obrigatórias e o valor padrão para desconto é zero. */

CREATE TABLE VENDAS (
    CODIGO_PRODUTO NUMBER (10) NOT NULL,
    VALOR_UNITARIO NUMBER (30) NOT NULL,
    QUANTIDADE NUMBER(30) NOT NULL,
    DESCONTO NUMBER (30) NOT NULL    
)

INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES (1, 25, 10, 5);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(2, 13.5, 3, 0);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(3, 15, 2, 0);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(1, 10, 1, 0);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(5, 30, 1, 0);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(5, 30, 10, 15);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(4, 10, 12, 5);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(1, 25, 13, 5);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(2, 13.5, 15, 5);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(3,15,3,0);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(5,30,3,0);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(1,25,22,15);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(3,15,3,0);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(1,25,10,3);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(3,15,25,20);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(1,25,10,3);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(3,15,25,20);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(1,25,10,3);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(2,13.5,10,4);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(3, 15,10,4);
INSERT INTO VENDAS(CODIGO_PRODUTO, VALOR_UNITARIO, QUANTIDADE, DESCONTO) VALUES(5,30,10,1);
 
SELECT * FROM VENDAS

/* 2. Pesquise os itens que foram vendidos sem desconto. As colunas presentes no resultado da
consulta são: CODIGO_PRODUTO, VALOR_UNITARIO e DESCONTO. */



/*3. Pesquise os itens que foram vendidos com desconto. As colunas presentes no resultado da
consulta são: CODIGO_PRODUTO, VALOR_UNITARIO E O VALOR VENDIDO. OBS: O valor
vendido é igual ao VALOR_UNITARIO - (VALOR_UNITARIO*(DESCONTO/100)). */



/*4. Pesquise os itens que foram vendidos. As colunas presentes no resultado da consulta são:
CODIGO_PRODUTO, QUANTIDADE_VENDIDA, VALOR_UNITARIO, VALOR_VENDIDO,
VALOR_TOTAL. OBS: O VALOR_TOTAL é obtido pela fórmula: QUANTIDADE *
VALOR_VENDIDO. */
