CREATE TABLE CLIENTES(
    NOME VARCHAR2(100),
    CPF VARCHAR2(11),
    TELEFONE VARCHAR2(20),
    ENDERECO VARCHAR2(500),

    PRIMARY KEY(CPF)
);

CREATE TABLE CARROS(
    PLACA VARCHAR2(20),
    MARCA VARCHAR2(50),
    MODELO VARCHAR2(50),

    PRIMARY KEY (PLACA)
);

CREATE TABLE ACIDENTES (
    CODIGO NUMBER,
    DATA_ACIDENTE DATE,
    PLACA_CARRO VARCHAR2(20),
    CPF_CLIENTE VARCHAR2(11),

    PRIMARY KEY (CODIGO),
    FOREIGN KEY (PLACA_CARRO) REFERENCES CARROS(PLACA),
    FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTES(CPF)


);

ALTER TABLE CLIENTES ADD(EMAIL VARCHAR2(255));
ALTER TABLE CLIENTES DROP COLUMN EMAIL;

ALTER TABLE CARROS ADD(ANO_FAB NUMBER(4));
ALTER TABLE CARROS MODIFY(ANO_FAB NOT NULL);
ALTER TABLE CARROS DROP COLUMN ANO_FAB;

ALTER TABLE ACIDENTES ADD(LOCAL VARCHAR2(200)DEFAULT 'NÃO INFORMADO');
ALTER TABLE ACIDENTES MODIFY (LOCAL NOT NULL);
ALTER TABLE ACIDENTES DROP COLUMN LOCAL

INSERT INTO CLIENTES (NOME, CPF, TELEFONE, ENDERECO) VALUES
('Ana Beatriz', '11111111111','(83)98745-1001','Rua das Pitombas,256 - João Pessoa/PB');

INSERT INTO CLIENTES (NOME, CPF, TELEFONE, ENDERECO) VALUES
('Bruna Castro', '22222222222','(83)98652-1123','Av. das Laranjas, 512 - João Pessoa/PB');

INSERT INTO CLIENTES (NOME, CPF, TELEFONE, ENDERECO) VALUES
('Cristina Silva', '33333333333','(83)98752-5293','Avenida do Limoeiro, 125 - João Pessoa/PB');

INSERT INTO CLIENTES (NOME, CPF, TELEFONE, ENDERECO) VALUES
('Daniel de Pádua','44444444444','(83)98652-5412','Rua das Jabuticabas,32 - João Pessoa/PB');

INSERT INTO CLIENTES (NOME, CPF, TELEFONE, ENDERECO) VALUES
('Estephany da Costa','55555555555','(83)98854-8875','Rua da Acerolas, 64 - João Pessoa/PB');


INSERT INTO CARROS (PLACA, MARCA, MODELO) VALUES 
('GTY-5412','BYD','DOLPHY');

INSERT INTO CARROS (PLACA, MARCA, MODELO) VALUES 
('OGA-8563','FIAT','PULSE');

INSERT INTO CARROS (PLACA, MARCA, MODELO) VALUES 
('XTG-9563','CHEVROLET','PRISMA');

INSERT INTO CARROS (PLACA, MARCA, MODELO) VALUES 
('DIT-5104','RENAULT','KARDIAN');

INSERT INTO CARROS (PLACA, MARCA, MODELO) VALUES 
('VIX-9854','CHEVROLET','ÔNIX');


INSERT INTO ACIDENTES (CODIGO, DATA_ACIDENTE, PLACA_CARRO,CPF_CLIENTE) VALUES 
(1,TO_DATE('04/09/2025', 'DD/MM/YYYY'),'GTY-5412', '11111111111');

INSERT INTO ACIDENTES (CODIGO, DATA_ACIDENTE, PLACA_CARRO,CPF_CLIENTE) VALUES 
(2,TO_DATE('17/09/2025', 'DD/MM/YYYY' ), 'OGA-8563', '22222222222');

INSERT INTO ACIDENTES (CODIGO, DATA_ACIDENTE, PLACA_CARRO, CPF_CLIENTE) VALUES
(3,TO_DATE('23/09/2025', 'DD/MM/YYYY' ), 'XTG-9563', '33333333333');

SELECT * FROM CLIENTES WHERE 
SELECT nome FROM CLIENTES WHERE nome = 'Bruna Castro'
SELECT * FROM CARROS
SELECT * FROM ACIDENTES
